[package]
name = "shadow_lock"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
base64 = "0.22.1"
blake3 = "1.8.1"
clap = { version = "4.3.0", features = ["derive"] }
dialoguer = "0.11.0"
dirs = "6.0.0"
dotenv = "0.15.0"
